#' Performs GSEA for all Hotgenes contrasts
#' @param HotgenesObj R object generated by DEseq2_export function
#' @param nTop number of pathways to return
#' @param m_df GeneSet generated using msigdbr function
#' @inheritParams fgsea::fgsea
#' @importFrom stats reorder
#' @return HotgenesObj appended with GSEA for each contrast
#' @export
#' @examples Example_Hotgenes_dir<-system.file("extdata",
#' "Example_Hotgenes.Rdata",
#' package = "Hotgenes", mustWork = TRUE)
#' load(Example_Hotgenes_dir)
#' library(msigdbr)
#' m_df = msigdbr(species = "Homo sapiens", category = "C5", subcategory = "BP")
#' qbat<-BatchGSEA(m_df= m_df, HotgenesObj=Example_Hotgenes)
#' summary(qbat)
#' qbat$OuputGSEA$Hrs2$g

BatchGSEA<-function(m_df=NULL, HotgenesObj=NULL,
nTop=10,
minSize=15,
maxSize=1000,
nperm=100000,
nproc=4){


m_list = split(x = m_df$gene_symbol, f = m_df$gs_name)

# fixing names
names(m_list)<-gsub("_", " ", fixed = TRUE, names(m_list))

contrast_name<-names(HotgenesObj$Output_DE)
contrast_name_lists <- setNames(vector(length(contrast_name),
mode="list"), contrast_name)


for(DE_sel in contrast_name){

clean_table<-HotgenesObj$Output_DE[[DE_sel]]
ranks<-clean_table[order(clean_table$stat, decreasing = TRUE),]
Gene_Ranks <- ranks$stat
names(Gene_Ranks) <- rownames(ranks)

# fgsea of pathways -------------------------------------------------------
fgseaRes <- fgsea::fgsea(pathways = m_list, 
stats = Gene_Ranks,
minSize=minSize,
maxSize=maxSize,
nperm=nperm,
nproc=nproc)

fgRes<-fgseaRes[fgseaRes$padj<0.1,]

# Filtering
Up <- head(fgRes[order(fgRes$NES, decreasing = TRUE)], n=nTop)
Down <- head(fgRes[order(fgRes$NES, decreasing = TRUE)], n = nTop)

top<-rbind(Up,Down)

top$pathway = stringr::str_replace(top$pathway, "GO " , "")
top$Enrichment = ifelse(top$NES > 0, "Up-regulated", "Down-regulated")

filtRes = top
filtRes$pathway<-stringr::str_wrap(filtRes$pathway, 50)

# plot
g <- ggplot(filtRes, aes(reorder(.data$pathway, .data$NES), .data$NES)) +
geom_segment(aes(reorder(.data$pathway, .data$NES),
xend=.data$pathway, y=0, yend=.data$NES)) +
geom_point(size=3, aes(fill = .data$Enrichment),
shape=21, stroke=0.6) +
scale_fill_manual(values = c("Down-regulated" = "dodgerblue",
"Up-regulated" = "firebrick") ) +
coord_flip() +
labs(x="Pathway", y="Normalized Enrichment Score") +
theme_minimal(base_size = 8) +
theme(axis.text  = element_text(size=8))


GSEA_OUT<-list(fgRes=fgRes,
top=top,
g=g)

contrast_name_lists[[DE_sel]]<-GSEA_OUT

}

HotgenesObj$OuputGSEA<-contrast_name_lists
return(HotgenesObj)
}




