#' R shiny app for visualizing DE analysis
#' @import shiny
#' @import pheatmap
#' @import RColorBrewer
#' @importFrom data.table melt
#' @importFrom plyr ldply
#' @importFrom utils read.csv
#' @param DEseq2_export R object generated by DEseq2_export function
#' @return a shiny object for network visualization.
#' @export
#' @return a shiny UI and server for visualization.
#' @examples Example_Hotgenes_dir<-system.file("extdata",
#' "Example_Hotgenes.Rdata",
#' package = "Hotgenes", mustWork = TRUE)
#' load(Example_Hotgenes_dir)
#' if(interactive()){
#' Shiny_DE_viz(Example_Hotgenes)}

Shiny_DE_viz<-function(DEseq2_export=NULL){


# FactoMiner Functions ----------------------------------------------------
Quanti_Table<-function(res.hcpc, Round_To){

# Variable
df_quanti <- plyr::ldply(res.hcpc$desc.var$quanti, data.frame)
df_quanti$Variable<- names(do.call(rbind,res.hcpc$desc.var$quanti)[,1])
df_quanti<-df_quanti[c(1,8,2:7)]
colnames(df_quanti)<-gsub(".id", "Groups", fixed = TRUE, colnames(df_quanti))

# round only numeric columns
numeric_colnames<-colnames(dplyr::select_if(df_quanti, is.numeric))
df_quanti[,numeric_colnames]<-round(df_quanti[,numeric_colnames], Round_To)

df_quanti<-df_quanti[,seq(1,5)]
df_quanti$Variable<-gsub(".", " ", df_quanti$Variable, fixed = TRUE)
colnames(df_quanti)<-gsub(".", " ",colnames(df_quanti), fixed = TRUE)
colnames(df_quanti)<-gsub("Variable", "Genes",colnames(df_quanti), fixed = TRUE)

return(df_quanti)
}

# Categorical table ------------------------------------------------------------
Categorical_Table<-function(res.hcpc, Round_To){

# Categories
df_cat <- plyr::ldply(res.hcpc$desc.var$category, data.frame)
colnames(df_cat)<-gsub(".id", "Groups", fixed = TRUE, colnames(df_cat))
df_cat$Category<- names(do.call(rbind,res.hcpc$desc.var$category)[,1])

df_cat$Category<-gsub("_"," ",fixed = TRUE,
df_cat$Category)

df_cat$Category<-gsub("=",": ",fixed = TRUE,
df_cat$Category)
df_cat<-df_cat[c(1,7,2:6)]

# round numeric columns
numeric_colnames<-colnames(dplyr::select_if(df_cat, is.numeric))
df_cat[,numeric_colnames]<-round(df_cat[,numeric_colnames], Round_To)

df_cat$p.value<-NULL
colnames(df_cat)<-gsub(".", " ", colnames(df_cat), fixed = TRUE)
col_percent<-colnames(df_cat[c(3:5)])

for (i in col_percent) {
df_cat[,c(i)]<-paste(df_cat[,c(i)], "%", sep = "")
}

return(df_cat)
}

# Table_Express ---------------------------------------------
Table_Express<-function(df_cat){
EqDatedf_cat <- as.data.frame(df_cat[1,])

cat_cols<-colnames(df_cat)
df_cat_lists <- setNames(vector(length(cat_cols), mode="list"), cat_cols)

for (i in cat_cols){
df_cat_lists[[i]]<-("")
}
EmptyLine <- data.frame(df_cat_lists, check.names = FALSE)


for (i in 2:nrow(df_cat)){
if(as.vector(df_cat$Groups[i])  ==  as.vector(df_cat$Groups[i-1])){
EqDatedf_cat <- rbind(EqDatedf_cat, df_cat[i,])
} else {
EqDatedf_cat <- rbind(EqDatedf_cat, EmptyLine)
EqDatedf_cat <- rbind(EqDatedf_cat, df_cat[i,])
}
}

return(EqDatedf_cat)
}

# pheatmap function -------------------------------------------------------

Pheatmap_Viz<-function(DE_Input=NULL,
hotList=NULL,samples_ids=1,readouts=1,ncut=NULL,
selected_contrast=2,lfc_cut=0){

# selecting normalized data -----------------------------------------------

gene_levels<-DE_Input$Normalized_Expression[[readouts]]

# hotlist input
if(is.null(hotList)){
contrast_name<-names(DE_Input$Output_DE[selected_contrast])
contrast_name_lists <- setNames(vector(length(contrast_name),
mode="list"), contrast_name)

for (i in contrast_name) {
sig_ids<-rownames(DE_Input$Output_DE[[i]]
[abs(DE_Input$Output_DE[[i]]$log2FoldChange)>=lfc_cut,])
contrast_name_lists[[i]]<-sig_ids
}

gene_ids<-unique(unlist(contrast_name_lists, use.names = FALSE))

} else if(!is.null(hotList)){
contrast_name<-NULL
lfc_cut<-NULL
ncut<-NULL
gene_ids<-hotList
}

if(is.null(ncut)){
ncut<-length(gene_ids)
gene_id_cut<-gene_ids[seq(1,ncut)]
}else if(!is.null(ncut)){
gene_id_cut<-gene_ids[seq(1,ncut)]
}
dm <- gene_levels[gene_id_cut,samples_ids]
return(dm)
}


habillage_choices<-c("clust", names(DEseq2_export$design_data))

# Contrast labels
FactoMiner_PCA<-data.frame(row.names=names(DEseq2_export$Output_lists),
name=names(DEseq2_export$Output_lists),
value=names(DEseq2_export$Output_lists),
stringsAsFactors = FALSE)

for(i in names(DEseq2_export$Output_lists)){
FactoMiner_PCA[i,"Total genes"]<-length(DEseq2_export$Output_lists[[i]])
}

FactoMiner_PCA$name<-paste(FactoMiner_PCA$name,
FactoMiner_PCA$`Total genes`,
sep = " genes: ")


# tab2 DE tables ----------------------------------------------------------
DEseq2_coefficients<-DEseq2_export$Output_DE
DE_ids<-names(DEseq2_coefficients)


# Tab3_Pheatmap samples ids -----------------------------------------------
Phea_ids<-colnames(DEseq2_export$Normalized_Expression[[1]])

bxplotIDS<-names(DEseq2_export$Exported_plots)
bxplotIDS<-bxplotIDS[bxplotIDS != "transformation_plots"]


# UI ------------------------------------------------------------------

ui <- fluidPage(
sidebarLayout(sidebarPanel(width = 3,


# tab alpha ---------------------------------------------------------------

conditionalPanel('input.dataset === "bxplotIDS"',
downloadButton(outputId = "downalpha", label = "Download the plot"),

# Input: Checkbox for query node color  ----
radioButtons(inputId = "Norm_viz",
label = "Visualize Normalization methods:",
inline  = FALSE,
choices =  bxplotIDS,
selected = bxplotIDS[1])),


# tab1 DE frames -----------------------------------------------------------
conditionalPanel('input.dataset === "FactoMiner_PCA"',

downloadButton(outputId = "down1", label = "Download the plot"),


# Input: Normalization method PCA -----------------------------------------


radioButtons(inputId = "PCA_Norm_selection",
label = "Normalization selection:",
inline  = TRUE,
choices =  names(DEseq2_export$Normalized_Expression),
selected = names(DEseq2_export$Normalized_Expression)[1]),


# Input: Checkbox for query node color  ----
checkboxGroupInput(inputId = "Contrasts",
label = "Contrasts selection:",
inline  = FALSE,
choiceNames =  FactoMiner_PCA[,1],
choiceValues = FactoMiner_PCA[,2],
selected = FactoMiner_PCA[1,2]),



# point size
sliderInput(inputId = "point_size",
label = "point size",
value = 3,
min = 1,
max = 10,
step = 1),

# label_size
sliderInput(inputId = "label_size",
label = "label size:",
value = 3,
min = 1,
max = 10,
step = 1),

# ellipse.level
sliderInput(inputId = "ellipse.level",
label = "ellipse level:",
value = 0.5,
min = 0,
max = 1,
step = 0.05),

# ellipse.level
sliderInput(inputId = "ellipse.alpha",
label = "ellipse alpha:",
value = 0,
min = 0,
max = 1,
step = 0.05),

# Input: Checkbox for query node color  ----
radioButtons(inputId = "habillage_id",
label = "Color by:",
inline  = FALSE,
choices =  habillage_choices),


# Input: Checkbox for Contrast selection  ----
radioButtons(inputId = "Biplot",
label = "Show Genes:",
inline  = FALSE,
choices =  c(FALSE, TRUE)),

# number of genes to show
numericInput(inputId = "Var",
label = "# of Genes:",
value = 10,
min = 1,
max = 30000,
step = 1)),


# tab2 DE frames -----------------------------------------------------------
conditionalPanel('input.dataset === "DEseq2_coefficients"', # DEseq2_coefficients
# Input: Checkbox for query node color  ----
radioButtons(inputId = "DE_Contrasts",
label = "Contrasts selection:",
inline  = FALSE,
choices =  DE_ids )),



# Tab3_Pheatmap -----------------------------------------------------------
conditionalPanel('input.dataset === "DEseq2_export"', # DEseq2_coefficients
downloadButton(outputId = "down2", label = "Download the plot"),

#input hotlist #annotations1
fileInput(inputId = "hotlist",
label = "Upload Hotlist",
accept = c(
"text/csv",
"text/comma-separated-values,text/plain",
".csv")),

#input annotations1
fileInput(inputId = "annotations",
label = "Upload PhenoData",
accept = c(
"text/csv",
"text/comma-separated-values,text/plain",
".csv")),

radioButtons(inputId = "annotation_legend",
label = "Show annotation legend:",
inline  = TRUE,
choices =  c(TRUE, FALSE)),

# Input: contrasts
radioButtons(inputId = "DE_Contrasts2",
label = "Contrasts selection:",
inline  = FALSE,
choiceNames =  FactoMiner_PCA[,1],
choiceValues = FactoMiner_PCA[,2],
selected = FactoMiner_PCA[1,2]),



# Input: Normalization method Pheatmap ------------------------------------


radioButtons(inputId = "Norm_selection",
label = "Normalization selection:",
inline  = TRUE,
choices =  names(DEseq2_export$Normalized_Expression),
selected = names(DEseq2_export$Normalized_Expression)[1]),

radioButtons(inputId = "col_pal",
label = "Color schemes:",
inline  = TRUE,
choices =  c("BrBG", "PiYG", "PRGn", "PuOr", "RdBu",  "RdYlBu"),
selected = c("BrBG", "PiYG", "PRGn", "PuOr", "RdBu",  "RdYlBu")[6]),

# number of genes to show
sliderInput(inputId = "CR",
label = "Color Ramp:",
value = 10,
min = 1,
max = 50,
step = 1),


radioButtons(inputId = "CC",
label = "Cluster:",
inline  = TRUE,
choices =  c(TRUE, FALSE)),




# Cut rows
sliderInput(inputId = "col_cut",
label = "Sample groups:",
value = 2,
min = 1,
max = 10,
step = 1),


# Cut rows
sliderInput(inputId = "row_cut",
label = "Gene groups:",
value = 2,
min = 1,
max = 10,
step = 1),


# point size
sliderInput(inputId = "W",
label = "Cell Width:",
value = 10,
min = 1,
max = 30,
step = 1),

# label_size
sliderInput(inputId = "H",
label = "Cell Height:",
value = 10,
min = 1,
max = 30,
step = 1),

# number of genes to show
numericInput(inputId = "Var2",
label = "Top significant Genes:",
value = 10,
min = 1,
max = 30000,
step = 1),

# number of genes to show
numericInput(inputId = "lfc",
label = "Abs lfc cut:",
value = 0,
min = 0,
max = 20,
step = 1),


checkboxGroupInput(inputId = "Samples",
label = "Sample selection:",
inline  = TRUE,
choices =  Phea_ids,
#choiceValues = Phea_ids[,2],
selected = Phea_ids)) ),



# tabs and mainpanels -----------------------------------------------------


mainPanel(tabsetPanel(id = 'dataset',
tabPanel(title = "Normalization QC",
value="bxplotIDS",plotOutput(outputId = "G_plots") ,
plotOutput(outputId = "Exporto_plots")),

tabPanel(title = "Search for Hotgenes",
value = "FactoMiner_PCA", plotOutput(outputId = "PCA_plot"),
DT::dataTableOutput("tab1.1_Query"),DT::dataTableOutput("tab1.2_Query")),

tabPanel("DEseq2_coefficients", DT::dataTableOutput("tab2_Query")),
tabPanel(title = "Heatmap", value = "DEseq2_export",
plotOutput(outputId = "pheat_plot",
width = "100%", height = "700px")) ))))


# server --------------------------------------------------------------


server <- function(input, output, session) {

# Tab2
output$tab2_Query<- DT::renderDataTable({
DT::datatable(DEseq2_coefficients[[input$DE_Contrasts]],filter = 'top',
extensions = 'Buttons',
options = list(dom = 'Bfrtip',pageLength = -1,
buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))) })

# Tab1.1
output$tab1.1_Query<- DT::renderDataTable({
DT::datatable(output_Conditions_table(),
rownames = FALSE, filter = 'top',
extensions = 'Buttons',
options = list(dom = 'Bfrtip',pageLength = -1,
buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))) })



# Tab1.2
output$tab1.2_Query<- DT::renderDataTable({gene_tab()})
gene_tab<-reactive({ DT::datatable(output_Gene_table(),
rownames = FALSE, filter = 'top',
selection = list(target = 'cell'),
extensions = 'Buttons',
options = list(dom = 'Bfrtip', pageLength = -1,
buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))) })



# Tab3_Pheatmap pheatmap
# output tab1 plot
hotlist_input<-reactive({

input_file_path<-input$hotlist
if(!is.null(input_file_path)){
hot1 <- read.csv(input_file_path$datapath, stringsAsFactors=FALSE)
hotlist<-unique(hot1$Genes)
}else if(is.null(input_file_path)){
hotlist=NULL}
print(hotlist)
})

annotation_input<-reactive({

annotations_file_path<-input$annotations
if(!is.null(annotations_file_path)){
annotations <- data.frame(read.csv(annotations_file_path$datapath,
row.names=1, stringsAsFactors=FALSE))
}else if(is.null(annotations_file_path)){
annotations=NULL}
print(annotations)

})


pheat_p <- reactive({

dm<-Pheatmap_Viz(DE_Input = DEseq2_export,
# filename= "ph.pdf",
hotList = hotlist_input(),
samples_ids = input$Samples,
ncut=input$Var2,
readouts=input$Norm_selection,
selected_contrast=input$DE_Contrasts2,
lfc_cut=input$lfc)



pheatmap(dm,
annotation_legend=as.logical(input$annotation_legend),
annotation_col=annotation_input(),
scale = "row",
border_color= "white",
cutree_rows=input$row_cut,
cutree_cols=input$col_cut,
fontsize_row=input$H,
fontsize_col=input$W,
cellwidth=input$W,
cellheight=input$H,
treeheight_row=10,
treeheight_col=10,
cluster_cols=as.logical(input$CC),
cluster_rows=TRUE,
color = colorRampPalette(rev(brewer.pal(n = 9, name =input$col_pal)))(input$CR))


})

output$pheat_plot <- renderPlot({pheat_p()})



output_temp<-reactive({

PCA_report<-FactoWrapper(Output_DEseq2 = DEseq2_export,
readouts=input$PCA_Norm_selection,
habillage_selection=input$habillage_id,
#readouts="rlog",
biplot=input$Biplot,
#View_by_sample=TRUE,
Top_var=input$Var,
ellipse.level=input$ellipse.level,
ellipse.alpha=input$ellipse.alpha,
label_sel=c("ind", "var"),
selected_contrast=input$Contrasts,
labelsize = input$label_size,
pointsize = input$point_size  )
})

# downalpha plot
output$downalpha <- downloadHandler(
filename =  function() {
paste("Norm_plots", "pdf", sep=".")
},
# content is a function with argument file.content writes the plot to the device
content = function(file) {

pdf(file) # open the pdf device
print(output_norm())
dev.off()  # turn the device off
} )




## call the plot function when downloading the image
output$down1 <- downloadHandler(
filename =  function() {
paste("PCA_plot", "pdf", sep=".")
},
# content is a function with argument file.content writes the plot to the device
content = function(file) {

pdf(file) # open the pdf device
print(output_temp())
dev.off()  # turn the device off
} )


## call the plot function when downloading the image
output$down2 <- downloadHandler(
filename =  function() {
paste("heatmap", "pdf", sep=".")
},
# content is a function with argument file.content writes the plot to the device
content = function(file) {
pdf(file) # open the pdf device
print(pheat_p())
dev.off()  # turn the device off
} )


# output tab alpha G_plots

output$G_plots<-renderPlot({
DEseq2_export$Exported_plots$transformation_plots
})


# output tab alpha   Exporto_plots
output_norm <- reactive({
DEseq2_export$Exported_plots[input$Norm_viz]
})


output$Exporto_plots<-renderPlot({
output_norm()
})


# output tab1 plot
output$PCA_plot <- renderPlot({
output_temp()$res_PPI_pa_1
})


# output tab1 cat table
output_Conditions_table <- reactive({
Conditions_table<-Categorical_Table(output_temp()$res.hcpc,2)
print(Conditions_table)
})

# output tab1 gene table
output_Gene_table <- reactive({
Quanti_Table_2<-Quanti_Table(output_temp()$res.hcpc,2)
print(Quanti_Table_2)
})


}
shinyApp(ui, server)
}
