#' Wrapper for EnhancedVolcano
#' @export
#' @importFrom EnhancedVolcano EnhancedVolcano
#' @param Hotgenes_input R object generated by DEseq2_export or 
#' Limma_export functions
#' @param TopSig numeric indicating the number of genes to highlight,
#' based on pvalue.
#' @param stuffer is a positive number added or subtracted from pvalue 
#' or fold change values, used for x and y limits.
#' @param contrast name or numeric value to retrieve differential 
#' expression data. See names(Hotgenes_input$Output_DE).
#' @examples
#' Example_Hotgenes_dir<-system.file("extdata",
#' "Example_Hotgenes.Rdata",
#' package = "Hotgenes", mustWork = TRUE)
#' load(Example_Hotgenes_dir)
#' names(Example_Hotgenes_dir$Output_DE)
#' Vplot(Example_Hotgenes, TopSig=10, contrast = 1)

Vplot<-function(Hotgenes_input=NULL, 
                TopSig=1, stuffer=0.5,
                contrast=1){
    id_sel<-names(Hotgenes_input$Output_DE[contrast])

    plot_inputff<-Hotgenes_input$Output_DE[[id_sel]]
    pcut<-plot_inputff[(TopSig+1),"pvalue"]
    
    Final_sig<-length(plot_inputff[plot_inputff$pvalue < pcut,"pvalue"])
    print(Final_sig)
    
    xlim_min<-c(min(plot_inputff$log2FoldChange)-stuffer)
    xlim_max<-c(stuffer+max(plot_inputff$log2FoldChange))
    
    ylim_min<-c(min(-log10(plot_inputff$pvalue)-stuffer))
    ylim_max<-c(stuffer+max(-log10(plot_inputff$pvalue)))
    
    sdff<- EnhancedVolcano::EnhancedVolcano(plot_inputff,
                           lab = rownames(plot_inputff),
                           x = 'log2FoldChange', y = 'pvalue', 
                           xlim = c( xlim_min,xlim_max), 
                           ylim = c(ylim_min,ylim_max),
                           DrawConnectors = TRUE,
                           title = paste("Top ",Final_sig,": ",id_sel,
                                         sep = ""),
                           pCutoff = pcut,
                           FCcutoff = 0,
                           transcriptPointSize =3.0,
                           transcriptLabSize = 3.0) 
    
    
    return(sdff)}

